title: "RankForge AI Blog"
description: "SEO, Content Marketing & AI Insights"
url: "https://rankforgeai.247-workforce.com"   # domain only, no /blog
baseurl: "/blog"                                # path where the site lives
author: "RankForge Team"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - about.md

show_excerpts: true
